### ISSUE TITLE
Reflection Probe Volume - Constantly refreshes hierarchy

### ISSUE THREAD

**Issue by nukeandbeans** [Kerfuffles/SabreCSG-Volume-Addons#11]
Selecting a volume set to Reflection Probe causes the hierarchy to constantly refresh.

**Comment by nukeandbeans** [comment]
This issue appears to be deeper than a refresh. It seems like the probe is created every tick of `OnInspectorGUI` due to invalidation. Not sure how to go about this.

**Comment by Henry00IS** [comment]
Fix this if-sentence: https://github.com/Kerfuffles/SabreCSG-Volume-Addons/blob/e68ce88b4b7336810f307f5af8a9e53faa32110a/ReflectionProbeVolume/ReflectionProbeVolume.cs#L209

**Comment by nukeandbeans** [comment]
that fixed it! thanks!
