### ISSUE TITLE
Sound Volume

### ISSUE THREAD

**Issue by ghost** [Kerfuffles/SabreCSG-Volume-Addons#6]
Maybe a Volume that plays sounds when your in it? So like if I'm in a vent or something, I would want to play a different ambient sound.

**Comment by Henry00IS** [comment]
**Volumetric Audio for SabreCSG**

![image](https://user-images.githubusercontent.com/7905726/45254017-7080d300-b370-11e8-8b6e-f34f53ec8c3f.png)

[Volumetric Audio for SabreCSG](https://00laboratories.com/product/volumetric-audio-for-sabrecsg) allows you to realistically emit sound from 3D volumes. You have the full geometry editing tools of SabreCSG at your disposal with live in-editor audio preview. The perfect tool to provide your level with beautiful ambient sound.

This is a [SabreCSG Extension](http://sabrecsg.com/) and it requires the Free and Open Source [SabreCSG Level Design Tools](https://github.com/sabresaurus/SabreCSG) for Unity.

[Documentation](https://00laboratories.com/henry00/hosted/volumetric-audio-for-sabrecsg/Volumetric%20Audio%20for%20SabreCSG%20Documentation.pdf)
[WebGL Demo](https://00laboratories.com/henry00/hosted/volumetric-audio-for-sabrecsg/) (has some audio issues)
[Windows Demo](https://00laboratories.com/henry00/hosted/volumetric-audio-for-sabrecsg/Volumetric-Audio-for-SabreCSG-Windows.zip)

**Volumetric Audio Introduction**

Default Unity audio sources emit sound from a fixed position in space with a round radius. When you have long pipelines and you wish to hear water flowing through it, you’d have to place multiple audio sources to cover the length of the pipeline. It causes a very unrealistic experience where the player is able to hear that only parts of the pipeline emit the sound. Volumetric Audio solves this by emitting sound from the entire pipeline like anyone’d expect. When the player enters a volume the sound transitions from being a 3D source to a 2D experience, surrounding them completely allowing the player to truly immerse in the vast environment of sound with great realism.

**Features**

• Full geometry editing tools of SabreCSG to create volumetric audio volumes.
• Live in-editor audio preview, no need to enter play mode.
• Hot reloading support, C# recompilations during play are fully supported.
• Realistic volumetric audio with customizable blending between 3D and 2D audio.
• Combine multiple volumes together to share a single audio source with ease.

**Purchasing Links**

You can [purchase it directly from our website](https://00laboratories.com/product/volumetric-audio-for-sabrecsg).
You can [purchase it on the Unity asset store](https://assetstore.unity.com/publishers/20999).
